// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetMusicDir() {
  return window['go']['main']['App']['GetMusicDir']();
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}
