// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetClients():Promise<Array<main.ClientInfo>>;

export function GetLocalIP():Promise<string>;

export function GetMusicDir():Promise<string>;

export function GetPort():Promise<string>;
