// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetDeviceModes() {
  return window['go']['main']['App']['GetDeviceModes']();
}

export function GetDeviceNames() {
  return window['go']['main']['App']['GetDeviceNames']();
}

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetMusicDir() {
  return window['go']['main']['App']['GetMusicDir']();
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function GetWSClientIPs() {
  return window['go']['main']['App']['GetWSClientIPs']();
}

export function SendPlay(arg1, arg2) {
  return window['go']['main']['App']['SendPlay'](arg1, arg2);
}

export function SendStop(arg1) {
  return window['go']['main']['App']['SendStop'](arg1);
}

export function SetDeviceMode(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceMode'](arg1, arg2);
}

export function SetDeviceName(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceName'](arg1, arg2);
}
