// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetClients():Promise<Array<main.ClientInfo>>;

export function GetDeviceModes():Promise<Record<string, string>>;

export function GetDeviceNames():Promise<Record<string, string>>;

export function GetFileList():Promise<Array<main.fileInfo>>;

export function GetLocalIP():Promise<string>;

export function GetMusicDir():Promise<string>;

export function GetPort():Promise<string>;

export function GetWSClientIPs():Promise<Array<string>>;

export function SendPlay(arg1:string,arg2:string):Promise<string>;

export function SendStop(arg1:string):Promise<string>;

export function SetDeviceMode(arg1:string,arg2:string):Promise<string>;

export function SetDeviceName(arg1:string,arg2:string):Promise<string>;
